<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Extenso.Data.Entity" Version="10.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inferno\Inferno.csproj" />
  </ItemGroup>
</Project>