using Inferno.Localization;

namespace Inferno.Web.ContentManagement.Infrastructure
{
    public class LanguagePackInvariant : ILanguagePack
    {
        #region ILanguagePack Members

        public string CultureCode => null;

        public IDictionary<string, string> LocalizedStrings => new Dictionary<string, string>
        {
            { InfernoCmsLocalizableStrings.Blog.Categories, "Categories" },
            { InfernoCmsLocalizableStrings.Blog.ManageBlog, "Manage Blog" },
            { InfernoCmsLocalizableStrings.Blog.CategoryModel.Name, "Name" },
            { InfernoCmsLocalizableStrings.Blog.CategoryModel.UrlSlug, "URL Slug" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.CategoryId, "Category" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.DateCreatedUtc, "Date Created (UTC)" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.ExternalLink, "External Link" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.FullDescription, "Full Description" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.Headline, "Headline" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.MetaDescription, "Meta Description" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.MetaKeywords, "Meta Keywords" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.ShortDescription, "Short Description" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.Slug, "URL Slug" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.TeaserImageUrl, "Teaser Image URL" },
            { InfernoCmsLocalizableStrings.Blog.PostModel.UseExternalLink, "Use External Link" },
            { InfernoCmsLocalizableStrings.Blog.TagModel.Name, "Name" },
            { InfernoCmsLocalizableStrings.Blog.TagModel.UrlSlug, "URL Slug" },
            { InfernoCmsLocalizableStrings.Blog.PostedByXOnX, "Posted by {0} on {1}." },
            { InfernoCmsLocalizableStrings.Blog.Posts, "Posts" },
            { InfernoCmsLocalizableStrings.Blog.Tags, "Tags" },
            { InfernoCmsLocalizableStrings.Blog.Title, "Blog" },
            { InfernoCmsLocalizableStrings.ContentBlocks.AllPostsBlock.CategoryId, "Category" },
            { InfernoCmsLocalizableStrings.ContentBlocks.AllPostsBlock.FilterType, "Filter Type" },
            { InfernoCmsLocalizableStrings.ContentBlocks.AllPostsBlock.TagId, "Tag" },
            { InfernoCmsLocalizableStrings.ContentBlocks.CategoriesBlock.NumberOfCategories, "Number of Categories" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.EmailAddress, "Email Address" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.FormUrl, "Form URL" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.HtmlTemplate, "HTML Template" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.PleaseEnterCaptcha, "Please enter captcha validation field." },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.PleaseEnterCorrectCaptcha, "Please enter correct captcha validation field." },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.RedirectUrl, "Redirect URL (After Submit)" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.SaveResultIfNotRedirectPleaseClick, "If this page does not automatically redirect, please click the following link to continue:" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.SaveResultRedirect, "Redirect" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.ThankYouMessage, "'Thank You' Message" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.UseAjax, "Use Ajax" },
            { InfernoCmsLocalizableStrings.ContentBlocks.HtmlBlock.BodyContent, "Body Content" },
            { InfernoCmsLocalizableStrings.ContentBlocks.HtmlBlock.HelpText.BodyContent, "The HTML content to display." },
            { InfernoCmsLocalizableStrings.ContentBlocks.HtmlBlock.HelpText.Script, "Optional JavaScript to add to the page." },
            { InfernoCmsLocalizableStrings.ContentBlocks.HtmlBlock.Script, "Script" },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.HelpText.EmailAddress, "The email address to send the form values to." },
            { InfernoCmsLocalizableStrings.ContentBlocks.FormBlock.HelpText.FormUrl, "Specify URL to send the form values to or leave blank for default behavior (form values are emailed to the specified address)." },
            { InfernoCmsLocalizableStrings.ContentBlocks.LanguageSwitchBlock.CustomTemplatePath, "Custom Template Path" },
            { InfernoCmsLocalizableStrings.ContentBlocks.LanguageSwitchBlock.IncludeInvariant, "Include Invariant" },
            { InfernoCmsLocalizableStrings.ContentBlocks.LanguageSwitchBlock.InvariantText, "Invariant Text" },
            { InfernoCmsLocalizableStrings.ContentBlocks.LanguageSwitchBlock.Style, "Style" },
            { InfernoCmsLocalizableStrings.ContentBlocks.LanguageSwitchBlock.UseUrlPrefix, "Use URL Prefix" },
            { InfernoCmsLocalizableStrings.ContentBlocks.LastNPostsBlock.NumberOfEntries, "# of Entries" },
            { InfernoCmsLocalizableStrings.ContentBlocks.ManageContentBlocks, "Manage Content Blocks" },
            { InfernoCmsLocalizableStrings.ContentBlocks.ManageZones, "Manage Zones" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Model.BlockType, "Block Type" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Model.CustomTemplatePath, "Custom Template Path" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Model.IsEnabled, "Is Enabled" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Model.Order, "Order" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Model.Title, "Title" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Model.ZoneId, "Zone" },
            { InfernoCmsLocalizableStrings.ContentBlocks.NewsletterSubscriptionBlock.Email, "Email" },
            { InfernoCmsLocalizableStrings.ContentBlocks.NewsletterSubscriptionBlock.EmailPlaceholder, "Your E-Mail Address" },
            { InfernoCmsLocalizableStrings.ContentBlocks.NewsletterSubscriptionBlock.Name, "Name" },
            { InfernoCmsLocalizableStrings.ContentBlocks.NewsletterSubscriptionBlock.NamePlaceholder, "Your Name" },
            { InfernoCmsLocalizableStrings.ContentBlocks.NewsletterSubscriptionBlock.SignUpLabel, "Sign up for newsletters" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.AfterCloudRender, "After Cloud Render" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.AutoResize, "Auto Resize" },
            //{ InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.CenterX, "Center X" },
            //{ InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.CenterY, "Center Y" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.ClassPattern, "Class Pattern" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.Colors, "Colors" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.Delay, "Delay" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.EncodeURI, "Encode URI" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.FontSizeFrom, "Font Size From" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.FontSizeTo, "Font Size To" },
            //{ InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.Height, "Height" },
            //{ InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.HeightUnit, "Height Unit" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.RemoveOverflowing, "Remove Overflowing" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.Shape, "Shape" },
            { InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.Steps, "Steps" },
            //{ InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.Width, "Width" },
            //{ InfernoCmsLocalizableStrings.ContentBlocks.TagCloudBlock.WidthUnit, "Width Unit" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Title, "Content Blocks" },
            { InfernoCmsLocalizableStrings.ContentBlocks.VideoBlock.AutoPlay, "Auto Play" },
            { InfernoCmsLocalizableStrings.ContentBlocks.VideoBlock.ControlId, "Control ID" },
            { InfernoCmsLocalizableStrings.ContentBlocks.VideoBlock.Loop, "Loop" },
            { InfernoCmsLocalizableStrings.ContentBlocks.VideoBlock.ShowControls, "Show Controls" },
            { InfernoCmsLocalizableStrings.ContentBlocks.VideoBlock.Source, "Source" },
            { InfernoCmsLocalizableStrings.ContentBlocks.VideoBlock.Type, "Type" },
            { InfernoCmsLocalizableStrings.ContentBlocks.VideoBlock.VideoTagNotSupported, "Your browser is too old to support HTML5 Video. Please update your browser." },
            { InfernoCmsLocalizableStrings.ContentBlocks.ZoneModel.Name, "Name" },
            { InfernoCmsLocalizableStrings.ContentBlocks.Zones, "Zones" },
            { InfernoCmsLocalizableStrings.Localization.IsRTL, "Is Right-to-Left" },
            { InfernoCmsLocalizableStrings.Localization.LanguageModel.CultureCode, "Culture" },
            { InfernoCmsLocalizableStrings.Localization.LanguageModel.IsEnabled, "Enabled" },
            { InfernoCmsLocalizableStrings.Localization.LanguageModel.IsRTL, "Right-to-Left" },
            { InfernoCmsLocalizableStrings.Localization.LanguageModel.Name, "Name" },
            { InfernoCmsLocalizableStrings.Localization.LanguageModel.SortOrder, "Sort Order" },
            { InfernoCmsLocalizableStrings.Localization.Languages, "Languages" },
            { InfernoCmsLocalizableStrings.Localization.LocalizableStringModel.InvariantValue, "Invariant" },
            { InfernoCmsLocalizableStrings.Localization.LocalizableStringModel.Key, "Key" },
            { InfernoCmsLocalizableStrings.Localization.LocalizableStringModel.LocalizedValue, "Localized" },
            { InfernoCmsLocalizableStrings.Localization.LocalizableStrings, "Localizable Strings" },
            { InfernoCmsLocalizableStrings.Localization.Localize, "Localize" },
            { InfernoCmsLocalizableStrings.Localization.ManageLanguages, "Manage Languages" },
            { InfernoCmsLocalizableStrings.Localization.ManageLocalizableStrings, "Manage Localizable Strings" },
            { InfernoCmsLocalizableStrings.Localization.SelectLanguage, "Select Language" },
            { InfernoCmsLocalizableStrings.Localization.Title, "Localization" },
            { InfernoCmsLocalizableStrings.Localization.Translate, "Translate" },
            { InfernoCmsLocalizableStrings.Localization.Translations, "Translations" },
            { InfernoCmsLocalizableStrings.Media.FileBrowserTitle, "File Browser" },
            { InfernoCmsLocalizableStrings.Media.ManageMedia, "Manage Media" },
            { InfernoCmsLocalizableStrings.Media.Title, "Media" },
            { InfernoCmsLocalizableStrings.Menus.IsExternalUrl, "Is External Url" },
            { InfernoCmsLocalizableStrings.Menus.Items, "Items" },
            { InfernoCmsLocalizableStrings.Menus.ManageMenuItems, "Manage Menu Items" },
            { InfernoCmsLocalizableStrings.Menus.ManageMenus, "Manage Menus" },
            { InfernoCmsLocalizableStrings.Menus.MenuItemModel.CssClass, "CSS Class" },
            { InfernoCmsLocalizableStrings.Menus.MenuItemModel.Description, "Description" },
            { InfernoCmsLocalizableStrings.Menus.MenuItemModel.Enabled, "Enabled" },
            { InfernoCmsLocalizableStrings.Menus.MenuItemModel.Position, "Position" },
            { InfernoCmsLocalizableStrings.Menus.MenuItemModel.Text, "Text" },
            { InfernoCmsLocalizableStrings.Menus.MenuItemModel.Url, "Url" },
            { InfernoCmsLocalizableStrings.Menus.MenuItems, "Menu Items" },
            { InfernoCmsLocalizableStrings.Menus.MenuModel.Name, "Name" },
            { InfernoCmsLocalizableStrings.Menus.MenuModel.UrlFilter, "URL Filter" },
            { InfernoCmsLocalizableStrings.Menus.NewItem, "New Item" },
            { InfernoCmsLocalizableStrings.Menus.Title, "Menus" },
            { InfernoCmsLocalizableStrings.Messages.CircularRelationshipError, "That action would cause a circular relationship!" },
            { InfernoCmsLocalizableStrings.Messages.ConfirmClearLocalizableStrings, "Warning! This will remove all localized strings from the database. Are you sure you want to do this?" },
            { InfernoCmsLocalizableStrings.Messages.GetTranslationError, "There was an error when retrieving the translation." },
            { InfernoCmsLocalizableStrings.Messages.UpdateTranslationError, "There was an error when saving the translation." },
            { InfernoCmsLocalizableStrings.Messages.UpdateTranslationSuccess, "Successfully saved translation." },
            { InfernoCmsLocalizableStrings.Navigation.CMS, "CMS" },
            { InfernoCmsLocalizableStrings.Newsletters.ExportToCSV, "Export To CSV" },
            { InfernoCmsLocalizableStrings.Newsletters.Subscribers, "Subscribers" },
            { InfernoCmsLocalizableStrings.Newsletters.SuccessfullySignedUp, "You have successfully signed up for newsletters." },
            { InfernoCmsLocalizableStrings.Newsletters.Title, "Newsletters" },
            { InfernoCmsLocalizableStrings.Pages.CannotDeleteOnlyVersion, "Cannot delete the only version of a page. Create a new version first." },
            { InfernoCmsLocalizableStrings.Pages.History, "History" },
            { InfernoCmsLocalizableStrings.Pages.ManagePages, "Manage Pages" },
            { InfernoCmsLocalizableStrings.Pages.Page, "Page" },
            { InfernoCmsLocalizableStrings.Pages.PageHistory, "Page History" },
            { InfernoCmsLocalizableStrings.Pages.PageHistoryRestoreConfirm, "Are you sure you want to restore this version?" },
            { InfernoCmsLocalizableStrings.Pages.PageHistoryRestoreError, "There was an error when trying to restore the specified page version." },
            { InfernoCmsLocalizableStrings.Pages.PageHistoryRestoreSuccess, "Successfully restored specified page version." },
            { InfernoCmsLocalizableStrings.Pages.PageModel.IsEnabled, "Is Enabled" },
            { InfernoCmsLocalizableStrings.Pages.PageModel.Name, "Name" },
            { InfernoCmsLocalizableStrings.Pages.PageModel.Order, "Order" },
            { InfernoCmsLocalizableStrings.Pages.PageModel.PageTypeId, "Page Type" },
            { InfernoCmsLocalizableStrings.Pages.PageModel.Roles, "Roles" },
            { InfernoCmsLocalizableStrings.Pages.PageModel.ShowOnMenus, "Show on Menus" },
            { InfernoCmsLocalizableStrings.Pages.PageVersionModel.CultureCode, "Culture Code" },
            { InfernoCmsLocalizableStrings.Pages.PageVersionModel.DateCreated, "Date Created (UTC)" },
            { InfernoCmsLocalizableStrings.Pages.PageVersionModel.DateModified, "Date Modified (UTC)" },
            { InfernoCmsLocalizableStrings.Pages.PageVersionModel.IsDraft, "Is Draft" },
            { InfernoCmsLocalizableStrings.Pages.PageVersionModel.Slug, "URL Slug" },
            { InfernoCmsLocalizableStrings.Pages.PageVersionModel.Status, "Status" },
            { InfernoCmsLocalizableStrings.Pages.PageVersionModel.Title, "Title" },
            { InfernoCmsLocalizableStrings.Pages.PageTypeModel.DisplayTemplatePath, "Display Template Path" },
            { InfernoCmsLocalizableStrings.Pages.PageTypeModel.EditorTemplatePath, "Editor Template Path" },
            { InfernoCmsLocalizableStrings.Pages.PageTypeModel.LayoutPath, "Layout Path" },
            { InfernoCmsLocalizableStrings.Pages.PageTypeModel.Name, "Name" },
            { InfernoCmsLocalizableStrings.Pages.PageTypes.StandardPage.BodyContent, "Body Content" },
            { InfernoCmsLocalizableStrings.Pages.PageTypes.StandardPage.MetaDescription, "Meta Description" },
            { InfernoCmsLocalizableStrings.Pages.PageTypes.StandardPage.MetaKeywords, "Meta Keywords" },
            { InfernoCmsLocalizableStrings.Pages.PageTypes.StandardPage.MetaTitle, "Meta Title" },
            { InfernoCmsLocalizableStrings.Pages.PageTypes.Title, "Page Types" },
            { InfernoCmsLocalizableStrings.Pages.Restore, "Restore" },
            { InfernoCmsLocalizableStrings.Pages.RestoreVersion, "Restore Version" },
            { InfernoCmsLocalizableStrings.Pages.SelectPageToBeginEdit, "Select a page to begin editing." },
            { InfernoCmsLocalizableStrings.Pages.Tags, "Tags" },
            { InfernoCmsLocalizableStrings.Pages.Title, "Pages" },
            { InfernoCmsLocalizableStrings.Pages.Translations, "Translations" },
            { InfernoCmsLocalizableStrings.Pages.Versions, "Versions" },
            { InfernoCmsLocalizableStrings.Settings.Blog.AccessRestrictions, "Access Restrictions" },
            { InfernoCmsLocalizableStrings.Settings.Blog.DateFormat, "Date Format" },
            { InfernoCmsLocalizableStrings.Settings.Blog.ItemsPerPage, "# Items Per Page" },
            { InfernoCmsLocalizableStrings.Settings.Blog.MenuPosition, "Menu Position" },
            { InfernoCmsLocalizableStrings.Settings.Blog.PageTitle, "Page Title" },
            { InfernoCmsLocalizableStrings.Settings.Blog.ShowOnMenus, "Show on Menus" },
            { InfernoCmsLocalizableStrings.Settings.Blog.LayoutPathOverride, "Layout Path (Override)" },
            { InfernoCmsLocalizableStrings.Settings.Pages.NumberOfPageVersionsToKeep, "# Page Versions to Keep" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequency, "Change Frequency" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.Id, "ID" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.Location, "Location" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.Priority, "Priority" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequencies.Always, "Always" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequencies.Daily, "Daily" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequencies.Hourly, "Hourly" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequencies.Monthly, "Monthly" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequencies.Never, "Never" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequencies.Weekly, "Weekly" },
            { InfernoCmsLocalizableStrings.Sitemap.Model.ChangeFrequencies.Yearly, "Yearly" },
            { InfernoCmsLocalizableStrings.Sitemap.ConfirmGenerateFile, "Are you sure you want to generate a new XML sitemap file? Warning: This will replace the existing one." },
            { InfernoCmsLocalizableStrings.Sitemap.GenerateFile, "Generate File" },
            { InfernoCmsLocalizableStrings.Sitemap.GenerateFileError, "Error when generating XML sitemap file." },
            { InfernoCmsLocalizableStrings.Sitemap.GenerateFileSuccess, "Successfully generated XML sitemap file." },
            { InfernoCmsLocalizableStrings.Sitemap.Title, "Sitemap" },
            { InfernoCmsLocalizableStrings.Sitemap.XMLSitemap, "XML Sitemap" },
            { InfernoCmsLocalizableStrings.UserProfile.Newsletter.SubscribeToNewsletters, "Subscribe to Newsletters" },
        };

        #endregion ILanguagePack Members
    }
}