using Inferno.Localization;

namespace Inferno.Web.Infrastructure
{
    public class LanguagePackInvariant : ILanguagePack
    {
        #region ILanguagePack Members

        public string CultureCode => null;

        public IDictionary<string, string> LocalizedStrings => new Dictionary<string, string>
        {
            { InfernoWebLocalizableStrings.Dashboard.Administration, "Administration" },
            { InfernoWebLocalizableStrings.Dashboard.Frontend, "Frontend" },
            { InfernoWebLocalizableStrings.Dashboard.Title, "Dashboard" },

            { InfernoWebLocalizableStrings.General.Actions, "Actions" },
            { InfernoWebLocalizableStrings.General.Add, "Add" },
            { InfernoWebLocalizableStrings.General.AreYouSure, "Are you sure?" },
            { InfernoWebLocalizableStrings.General.Back, "Back" },
            { InfernoWebLocalizableStrings.General.Cancel, "Cancel" },
            { InfernoWebLocalizableStrings.General.Clear, "Clear" },
            { InfernoWebLocalizableStrings.General.Close, "Close" },
            { InfernoWebLocalizableStrings.General.Configuration, "Configuration" },
            { InfernoWebLocalizableStrings.General.Confirm, "Confirm" },
            { InfernoWebLocalizableStrings.General.ConfirmDeleteRecord, "Are you sure that you want to delete this record?" },
            { InfernoWebLocalizableStrings.General.Continue, "Continue" },
            { InfernoWebLocalizableStrings.General.Create, "Create" },
            { InfernoWebLocalizableStrings.General.CreateFormat, "Create {0}" },
            { InfernoWebLocalizableStrings.General.DateCreated, "Date Created" },
            { InfernoWebLocalizableStrings.General.DateCreatedUtc, "Date Created (UTC)" },
            { InfernoWebLocalizableStrings.General.DateModified, "Date Modified" },
            { InfernoWebLocalizableStrings.General.DateModifiedUtc, "Date Modified (UTC)" },
            { InfernoWebLocalizableStrings.General.Delete, "Delete" },
            { InfernoWebLocalizableStrings.General.DeleteRecordError, "There was an error when deleting the record." },
            { InfernoWebLocalizableStrings.General.DeleteRecordErrorFormat, "There was an error when deleting the record. Additional information as follows: {0}" },
            { InfernoWebLocalizableStrings.General.DeleteRecordSuccess, "Successfully deleted record." },
            { InfernoWebLocalizableStrings.General.Description, "Description" },
            { InfernoWebLocalizableStrings.General.Details, "Details" },
            { InfernoWebLocalizableStrings.General.Download, "Download" },
            { InfernoWebLocalizableStrings.General.Edit, "Edit" },
            { InfernoWebLocalizableStrings.General.EditFormat, "Edit {0}" },
            { InfernoWebLocalizableStrings.General.EditWithFormat, "Edit with {0}" },
            { InfernoWebLocalizableStrings.General.Enabled, "Enabled" },
            { InfernoWebLocalizableStrings.General.Error, "Error" },
            { InfernoWebLocalizableStrings.General.Export, "Export" },
            { InfernoWebLocalizableStrings.General.GetRecordError, "There was an error when retrieving the record." },
            { InfernoWebLocalizableStrings.General.Home, "Home" },
            { InfernoWebLocalizableStrings.General.Id, "ID" },
            { InfernoWebLocalizableStrings.General.Import, "Import" },
            { InfernoWebLocalizableStrings.General.InsertRecordError, "There was an error when inserting the record." },
            { InfernoWebLocalizableStrings.General.InsertRecordSuccess, "Successfully inserted record." },
            { InfernoWebLocalizableStrings.General.Install, "Install" },
            { InfernoWebLocalizableStrings.General.Loading, "Loading…" },
            { InfernoWebLocalizableStrings.General.Localize, "Localize" },
            { InfernoWebLocalizableStrings.General.Miscellaneous, "Miscellaneous" },
            { InfernoWebLocalizableStrings.General.Move, "Move" },
            { InfernoWebLocalizableStrings.General.Name, "Name" },
            { InfernoWebLocalizableStrings.General.Next, "Next" },
            { InfernoWebLocalizableStrings.General.None, "None" },
            { InfernoWebLocalizableStrings.General.OK, "OK" },
            { InfernoWebLocalizableStrings.General.OnOff, "On/Off" },
            { InfernoWebLocalizableStrings.General.Order, "Order" },
            { InfernoWebLocalizableStrings.General.PleaseWait, "Please Wait…" },
            { InfernoWebLocalizableStrings.General.Preview, "Preview" },
            { InfernoWebLocalizableStrings.General.Previous, "Previous" },
            { InfernoWebLocalizableStrings.General.Remove, "Remove" },
            { InfernoWebLocalizableStrings.General.Rename, "Rename" },
            { InfernoWebLocalizableStrings.General.Save, "Save" },
            { InfernoWebLocalizableStrings.General.SaveAndContinue, "Save & Continue" },
            { InfernoWebLocalizableStrings.General.Search, "Search" },
            { InfernoWebLocalizableStrings.General.SelectOption, "Select…" },
            { InfernoWebLocalizableStrings.General.Set, "Set" },
            { InfernoWebLocalizableStrings.General.SetDefault, "Set Default" },
            { InfernoWebLocalizableStrings.General.Settings, "Settings" },
            { InfernoWebLocalizableStrings.General.Slug, "URL Slug" },
            { InfernoWebLocalizableStrings.General.Submit, "Submit" },
            { InfernoWebLocalizableStrings.General.Success, "Success" },
            { InfernoWebLocalizableStrings.General.Themes, "Themes" },
            { InfernoWebLocalizableStrings.General.Toggle, "On/Off" },
            { InfernoWebLocalizableStrings.General.Uninstall, "Uninstall" },
            { InfernoWebLocalizableStrings.General.Unspecified, "Unspecified" },
            { InfernoWebLocalizableStrings.General.UpdateRecordError, "There was an error when updating the record." },
            { InfernoWebLocalizableStrings.General.UpdateRecordErrorFormat, "There was an error when updating the record. Additional information as follows: {0}" },
            { InfernoWebLocalizableStrings.General.UpdateRecordSuccess, "Successfully updated record." },
            { InfernoWebLocalizableStrings.General.Upload, "Upload" },
            { InfernoWebLocalizableStrings.General.View, "View" },
            { InfernoWebLocalizableStrings.General.ViewFormat, "View {0}" },

            { InfernoWebLocalizableStrings.Localization.IsRTL, "Is Right-to-Left" },
            { InfernoWebLocalizableStrings.Localization.LanguageModel.CultureCode, "Culture" },
            { InfernoWebLocalizableStrings.Localization.LanguageModel.IsEnabled, "Enabled" },
            { InfernoWebLocalizableStrings.Localization.LanguageModel.IsRTL, "Right-to-Left" },
            { InfernoWebLocalizableStrings.Localization.LanguageModel.Name, "Name" },
            { InfernoWebLocalizableStrings.Localization.LanguageModel.SortOrder, "Sort Order" },
            { InfernoWebLocalizableStrings.Localization.Languages, "Languages" },
            { InfernoWebLocalizableStrings.Localization.LocalizableStringModel.InvariantValue, "Invariant" },
            { InfernoWebLocalizableStrings.Localization.LocalizableStringModel.Key, "Key" },
            { InfernoWebLocalizableStrings.Localization.LocalizableStringModel.LocalizedValue, "Localized" },
            { InfernoWebLocalizableStrings.Localization.LocalizableStrings, "Localizable Strings" },
            { InfernoWebLocalizableStrings.Localization.Localize, "Localize" },
            { InfernoWebLocalizableStrings.Localization.ManageLanguages, "Manage Languages" },
            { InfernoWebLocalizableStrings.Localization.ManageLocalizableStrings, "Manage Localizable Strings" },
            { InfernoWebLocalizableStrings.Localization.SelectLanguage, "Select Language" },
            { InfernoWebLocalizableStrings.Localization.Title, "Localization" },
            { InfernoWebLocalizableStrings.Localization.Translate, "Translate" },
            { InfernoWebLocalizableStrings.Localization.Translations, "Translations" },

            { InfernoWebLocalizableStrings.Localization.ResetLocalizableStringsConfirm, "This will clear all the localizable strings in the database. Are you sure you want to do this?" },
            { InfernoWebLocalizableStrings.Localization.ResetLocalizableStringsError, "There was an error when resetting the localized strings." },
            { InfernoWebLocalizableStrings.Localization.ResetLocalizableStringsSuccess, "Successfully reset the localized strings." },

            { InfernoWebLocalizableStrings.Log.ClearConfirm, "Are you sure you want to clear the log?" },
            { InfernoWebLocalizableStrings.Log.ClearError, "Error when trying to clear the log." },
            { InfernoWebLocalizableStrings.Log.ClearSuccess, "Successfully cleared the log." },
            { InfernoWebLocalizableStrings.Log.Title, "Log" },
            { InfernoWebLocalizableStrings.Log.Model.ErrorClass, "Error Class" },
            { InfernoWebLocalizableStrings.Log.Model.ErrorMessage, "Error Message" },
            { InfernoWebLocalizableStrings.Log.Model.ErrorMethod, "Error Method" },
            { InfernoWebLocalizableStrings.Log.Model.ErrorSource, "Error Source" },
            { InfernoWebLocalizableStrings.Log.Model.EventDateTime, "Event Date/Time" },
            { InfernoWebLocalizableStrings.Log.Model.EventLevel, "Event Level" },
            { InfernoWebLocalizableStrings.Log.Model.EventMessage, "Event Message" },
            { InfernoWebLocalizableStrings.Log.Model.InnerErrorMessage, "Inner Error Message" },
            { InfernoWebLocalizableStrings.Log.Model.MachineName, "Machine Name" },
            { InfernoWebLocalizableStrings.Log.Model.UserName, "Username" },

            { InfernoWebLocalizableStrings.Maintenance.Title, "Maintenance" },

            { InfernoWebLocalizableStrings.Membership.AllRolesSelectListOption, "[All Roles]" },
            { InfernoWebLocalizableStrings.Membership.ChangePassword, "Change Password" },
            { InfernoWebLocalizableStrings.Membership.ChangePasswordError, "There was an error when changing the password." },
            { InfernoWebLocalizableStrings.Membership.ChangePasswordModel.ConfirmPassword, "Confirm Password" },
            { InfernoWebLocalizableStrings.Membership.ChangePasswordModel.Password, "Password" },
            { InfernoWebLocalizableStrings.Membership.ChangePasswordModel.UserName, "Username" },
            { InfernoWebLocalizableStrings.Membership.ChangePasswordSuccess, "Successfully changed password." },
            { InfernoWebLocalizableStrings.Membership.EditRolePermissions, "Edit Role Permissions" },
            { InfernoWebLocalizableStrings.Membership.InsertUserError, "There was an error when trying to create the user." },
            { InfernoWebLocalizableStrings.Membership.InvalidEmailAddress, "That is not a valid e-mail address. Please check your input and try again." },
            { InfernoWebLocalizableStrings.Membership.IsLockedOut, "Is Locked Out" },
            { InfernoWebLocalizableStrings.Membership.Password, "Password" },
            { InfernoWebLocalizableStrings.Membership.PermissionModel.Category, "Category" },
            { InfernoWebLocalizableStrings.Membership.PermissionModel.Name, "Name" },
            { InfernoWebLocalizableStrings.Membership.Permissions, "Permissions" },
            { InfernoWebLocalizableStrings.Membership.RoleModel.Name, "Name" },
            { InfernoWebLocalizableStrings.Membership.Roles, "Roles" },
            { InfernoWebLocalizableStrings.Membership.SavePermissionsError, "There was an error when saving permissions." },
            { InfernoWebLocalizableStrings.Membership.SavePermissionsSuccess, "Successfully saved permissions." },
            { InfernoWebLocalizableStrings.Membership.SaveRolesError, "There was an error when saving roles." },
            { InfernoWebLocalizableStrings.Membership.SaveRolesSuccess, "Successfully saved roles." },
            { InfernoWebLocalizableStrings.Membership.Title, "Membership" },
            { InfernoWebLocalizableStrings.Membership.UpdateUserRoles, "Update User Roles" },
            { InfernoWebLocalizableStrings.Membership.UserEmailAlreadyExists, "A user with that e-mail address already exists. If you are the owner of that e-mail address, please login and try again." },
            { InfernoWebLocalizableStrings.Membership.UserModel.Email, "Email" },
            { InfernoWebLocalizableStrings.Membership.UserModel.IsActive, "Is Active" },
            { InfernoWebLocalizableStrings.Membership.UserModel.IsLockedOut, "Is Locked Out" },
            { InfernoWebLocalizableStrings.Membership.UserModel.Roles, "Roles" },
            { InfernoWebLocalizableStrings.Membership.UserModel.UserName, "Username" },
            { InfernoWebLocalizableStrings.Membership.Users, "Users" },

            { InfernoWebLocalizableStrings.Plugins.InstallPluginError, "There was an error when installing the plugin." },
            { InfernoWebLocalizableStrings.Plugins.InstallPluginSuccess, "Successfully installed the specified plugin." },
            { InfernoWebLocalizableStrings.Plugins.ManagePlugins, "Manage Plugins" },
            { InfernoWebLocalizableStrings.Plugins.Title, "Plugins" },
            { InfernoWebLocalizableStrings.Plugins.Model.Group, "Group" },
            { InfernoWebLocalizableStrings.Plugins.Model.PluginInfo, "Plugin Info" },
            { InfernoWebLocalizableStrings.Plugins.Model.DisplayOrder, "Display Order" },
            { InfernoWebLocalizableStrings.Plugins.Model.FriendlyName, "Friendly Name" },
            { InfernoWebLocalizableStrings.Plugins.Model.LimitedToTenants, "Limited to Tenants" },

            { InfernoWebLocalizableStrings.ScheduledTasks.ExecutedTaskError, "There was an error when executing the task." },
            { InfernoWebLocalizableStrings.ScheduledTasks.ExecutedTaskSuccess, "Successfully executed task." },
            { InfernoWebLocalizableStrings.ScheduledTasks.ManageScheduledTasks, "Manage Scheduled Tasks" },
            { InfernoWebLocalizableStrings.ScheduledTasks.RunNow, "Run Now" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Model.Enabled, "Is Enabled" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Model.LastEndUtc, "Last End (UTC)" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Model.LastStartUtc, "Last Start (UTC)" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Model.LastSuccessUtc, "Last Success (UTC)" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Model.Name, "Name" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Model.Seconds, "Seconds" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Model.StopOnError, "Stop On Error" },
            { InfernoWebLocalizableStrings.ScheduledTasks.Title, "Scheduled Tasks" },

            { InfernoWebLocalizableStrings.Settings.Membership.DisallowUnconfirmedUserLogin, "Disallow Unconfirmed User Login" },
            { InfernoWebLocalizableStrings.Settings.Membership.GeneratedPasswordLength, "Length" },
            { InfernoWebLocalizableStrings.Settings.Membership.GeneratedPasswordNumberOfNonAlphanumericChars, "# Non-Alphanumeric Characters" },

            { InfernoWebLocalizableStrings.Settings.Model.Name, "Name" },

            { InfernoWebLocalizableStrings.Settings.Site.AdminLayoutPath, "Admin Layout Path" },
            { InfernoWebLocalizableStrings.Settings.Site.AllowUserToSelectTheme, "Allow User To Select Theme" },
            { InfernoWebLocalizableStrings.Settings.Site.DefaultFrontendLayoutPath, "Default Frontend Layout Path" },
            { InfernoWebLocalizableStrings.Settings.Site.DefaultGridPageSize, "Default Grid Page Size" },
            { InfernoWebLocalizableStrings.Settings.Site.DefaultLanguage, "Default Language" },
            { InfernoWebLocalizableStrings.Settings.Site.DefaultMetaDescription, "Default Meta Description" },
            { InfernoWebLocalizableStrings.Settings.Site.DefaultMetaKeywords, "Default Meta Keywords" },
            { InfernoWebLocalizableStrings.Settings.Site.DefaultTheme, "Default Theme" },
            { InfernoWebLocalizableStrings.Settings.Site.HomePageTitle, "Home Page Title" },
            { InfernoWebLocalizableStrings.Settings.Site.SiteName, "Site Name" },
            { InfernoWebLocalizableStrings.Settings.Site.Tabs.General, "General" },
            { InfernoWebLocalizableStrings.Settings.Site.Tabs.Localization, "Localization" },
            { InfernoWebLocalizableStrings.Settings.Site.Tabs.SEO, "SEO" },
            { InfernoWebLocalizableStrings.Settings.Site.Tabs.Themes, "Themes" },

            { InfernoWebLocalizableStrings.Tenants.ManageTenants, "Manage Tenants" },
            { InfernoWebLocalizableStrings.Tenants.Model.Hosts, "Hosts" },
            { InfernoWebLocalizableStrings.Tenants.Model.Url, "URL" },
            { InfernoWebLocalizableStrings.Tenants.Title, "Tenants" },

            { InfernoWebLocalizableStrings.Themes.Model.IsDefaultTheme, "Default Theme" },
            { InfernoWebLocalizableStrings.Themes.Model.PreviewImageUrl, "Preview" },
            { InfernoWebLocalizableStrings.Themes.Model.SupportRtl, "Supports RTL" },
            { InfernoWebLocalizableStrings.Themes.SetDesktopThemeError, "Error when setting default desktop theme." },
            { InfernoWebLocalizableStrings.Themes.SetDesktopThemeSuccess, "Successfully set default desktop theme." },
            { InfernoWebLocalizableStrings.Themes.SetMobileThemeError, "Error when setting default mobile theme." },
            { InfernoWebLocalizableStrings.Themes.SetMobileThemeSuccess, "Successfully set default mobile theme." },

            { InfernoWebLocalizableStrings.UserProfile.Account.FamilyName, "Family Name" },
            { InfernoWebLocalizableStrings.UserProfile.Account.GivenNames, "Given Name/s" },
            { InfernoWebLocalizableStrings.UserProfile.Account.ShowFamilyNameFirst, "Show Family Name First" },
            { InfernoWebLocalizableStrings.UserProfile.Localization.PreferredLanguage, "Preferred Language" },
            { InfernoWebLocalizableStrings.UserProfile.Mobile.DontUseMobileVersion, "Don't Use Mobile Version" },
            { InfernoWebLocalizableStrings.UserProfile.Theme.PreferredTheme, "Preferred Theme" },
        };

        #endregion ILanguagePack Members
    }
}